### ISSUE TITLE
Templates worked for me after one change...

### ISSUE THREAD

**Issue by Stephen-McDaniel** [JohnCoene/ambiorix#38] opened 2021-02-17 21:08 UTC
Before import("views"), I needed to add a working directory at the root of template app:

<pre>
# app.R is in /myapps/template01
setwd("/myapps/template01")
</pre>

Then it worked.  Without this addition, I observed this error:

<pre>
Error: [ENOENT] Failed to search directory '//views': no such file or directory
</pre>

Perhaps I overlooked a more elegant solution?

Best,
Stephen

**Comment by JohnCoene** [comment] 2022-02-22 22:42
Hmmm, I cannot reproduce it. I'll close this and will reopen in the future if it pops up again.

Thanks for reporting this, I may have inadvertently fixed it.

**Closed by JohnCoene** 2022-02-22 22:42 UTC
Labels: bug
